# ROS 2 Parameter File Example
#
# This file demonstrates parameter configuration for ROS 2 nodes.
# Load with: ros2 run package node --ros-args --params-file node_params.yaml

# Parameters for minimal_publisher node
minimal_publisher:
  ros__parameters:
    # Topic configuration
    topic_name: "chatter"
    publish_rate: 10.0  # Hz

    # Message content
    message_prefix: "Hello"
    use_counter: true

# Parameters for robot_controller node
robot_controller:
  ros__parameters:
    # Motion limits
    max_linear_speed: 1.0  # m/s
    max_angular_speed: 2.0  # rad/s

    # Control gains
    kp_linear: 1.0
    ki_linear: 0.1
    kd_linear: 0.05

    kp_angular: 2.0
    ki_angular: 0.2
    kd_angular: 0.1

    # Safety
    enable_safety_stop: true
    obstacle_distance_threshold: 0.5  # meters

# Global parameters (all nodes)
/**:
  ros__parameters:
    use_sim_time: false
    logging_level: "INFO"
